### ISSUE TITLE
Gautam, this statement is creating an error: "total_length = int(raw_image.headers['Content-Length'])"

### ISSUE THREAD

**Issue by ArpanDash** [AllMight420/4Anime-Downloader#3]
It says that "Content-Length" key is invalid.

I know Python, and looked through the raw_image.headers dictionary, but there's no "Content-Length" section present. This is a big issue.

**Comment by AllMight420** [comment]
It must be a server issue from 4Anime. You are unable to download certain episodes directly from the website sometimes due to this
